name: CI Pipeline

on:
  push:
    branches:
      - main  # Запускається при пуші в main
  pull_request:
    branches:
      - main  # Запускається при створенні/оновленні пул-реквесту в main

jobs:
  test:
    runs-on: ubuntu-latest  # Використовуємо останню версію Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Клонує репозиторій

      - name: Set up Python
        uses: actions/setup-python@v5  # Встановлює Python
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pygame pygame_gui  # Встановлюємо pytest та залежності

      - name: Run tests
        run: |
          pytest Tests/test_GameScreenModule.py -v  # Запускаємо тести