name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pygame==2.5.2 pygame_gui==0.6.9 pytest-mock

      - name: Run tests
        run: |
          pytest Tests/test_AbstractBonusObject.py -v
          pytest Tests/test_AdditionalBallsBonus.py -v
          pytest Tests/test_Ball.py -v
          pytest Tests/test_ExtendPlatformBonus.py -v
          pytest Tests/test_LevelManager.py -v
          pytest Tests/test_LevelPlate.py -v
          pytest Tests/test_SettingsViewController.py -v
          pytest Tests/test_UserPlate.py -v